server:
  servlet:
    context-path: /uaa
  port: 8081
  
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/currencydb
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   initialization-mode: always
 jpa:
   generate-ddl: true
   hibernate:
    ddl-auto: create
   show-sql: true
    
debug: true