server:
  servlet:
    context-path: /uaa
  port: 8081
  
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/currencydb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    
debug: true