server:
  servlet:
    context-path: /uaa
  port: 8081
  
spring:
 datasource:
  url: jdbc:mysql://localhost/currencydb
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

debug: true