spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  security:
    user:
      password: 1234

server:
  port: 8888 #the port where the config-server will be acessible