security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 1234
      accessTokenUri: http://localhost:8081/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /accounts
  port: 8082

feign:
  hystrix:
    enabled: true
    
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/uaa/user/current
      token-info-uri: http://localhost:8090/uaa/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000